bootrom = "dmg_boot.bin"
saves_dir = "saves"
volume = 25.0
scale = 3

[hotkeys.joypad]
up = "up"
down = "down"
left = "left"
right = "right"
a = "x"
b = "z"
start = "enter"
select = "tab"

[hotkeys.emu]
toggle_frame_limiter = "space"
